# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47df37cda0446e4de09019668461d7280e3ae4505095a75f6d63d5cc176016faf2b892d5dc9ad7bfc904064d068e50163c21a8474e8240571082c098816bec32

test:
  secret_key_base: 0be0e6ebb0e526837e36b29928162b63d69c204f990fdeeaf53310ed6f433934bb2aa7b34c7325ef367f88eac96386921ef8a1974ddc18d5045696550f16d346

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
